name: unity_checkin
description: Unity Mobil Giriş Çıkış Uygulaması.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  get: ^3.26.0
  package_info: ^2.0.0
  wifi_info_flutter: ^2.0.0
  permission_handler: ^6.0.1+1
  syncfusion_flutter_calendar: ^18.4.47
  syncfusion_localizations: ^18.4.47
  location: ^4.1.1
  email_validator: ^1.0.6
  shared_preferences: ^2.0.3
  fluttertoast: ^7.1.8
  image_picker: ^0.7.2
  url_launcher: ^6.0.2
  path_provider: ^2.0.1

  firebase_core: ^1.0.1
  firebase_messaging: ^9.0.0
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_crashlytics: ^1.0.0
  firebase_performance: ^0.6.0
  firebase_remote_config: ^0.9.0-dev.0
  firebase_analytics: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Redressed
      fonts:
        - asset: assets/fonts/Redressed-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf